const JOBS_DATA = [
    // --- INTERNSHIPS (1-15) ---
    {
        id: "job-101",
        title: "SDE Intern",
        company: "Amazon India",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹45k–₹80k/month",
        skills: ["Java", "DSA", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://amazon.jobs/en",
        description: "Join the Amazon India development team as an SDE Intern. You will work on scalable backend services, participate in code reviews, and learn best practices in distributed systems. Ideal for final year students."
    },
    {
        id: "job-102",
        title: "Frontend Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹30k–₹50k/month",
        skills: ["React", "JavaScript", "CSS"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://careers.swiggy.com",
        description: "Swiggy is looking for a passionate Frontend Intern to build delightful user interfaces. You will work closely with designers and product managers to ship features for our consumer app."
    },
    {
        id: "job-103",
        title: "Data Analyst Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹40k–₹60k/month",
        skills: ["SQL", "Python", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://flipkartcareers.com",
        description: "Analyze large datasets to derive actionable insights for our supply chain team. Proficiency in SQL and basic Python scripting is required. Great opportunity to learn e-commerce analytics."
    },
    {
        id: "job-104",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "3–4.5 LPA",
        skills: ["Java", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "https://tcs.com/careers",
        description: "TCS is hiring fresh graduates for the Digital Innovator role. Training provided in full-stack development. Strong problem-solving skills and willingness to relocate are essential."
    },
    {
        id: "job-105",
        title: "QA Intern",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹15k–₹25k/month",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Zoho Careers",
        postedDaysAgo: 3,
        applyUrl: "https://careers.zoho.com",
        description: "Learn the art of software quality assurance at Zoho. You will write test cases, perform manual testing, and get introduced to automation frameworks."
    },
    {
        id: "job-106",
        title: "Software Engineer Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹80k–₹1.2L/month",
        skills: ["C++", "C#", "Azure"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        applyUrl: "#",
        description: "Work on world-class products like Azure and Office 365. We are looking for students with strong algorithmic skills and a passion for building software that empowers everyone."
    },
    {
        id: "job-107",
        title: "Backend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        salaryRange: "₹40k–₹60k/month",
        skills: ["Go", "PHP", "MySQL"],
        source: "Indeed",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Help build the financial backbone of India. Work on high-performance payment gateways and APIs. Experience with Go or PHP is a plus."
    },
    {
        id: "job-108",
        title: "UI/UX Design Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹50k–₹80k/month",
        skills: ["Figma", "Prototyping", "Visual Design"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Join CRED's design team to create visually stunning and rewarding experiences. A strong portfolio showcasing UI exploration and attention to detail is mandatory."
    },
    {
        id: "job-109",
        title: "Research Intern",
        company: "Google Research India",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹1L–₹1.5L/month",
        skills: ["ML", "Python", "TensorFlow"],
        source: "Google Careers",
        postedDaysAgo: 9,
        applyUrl: "#",
        description: "Collaborate with research scientists on cutting-edge AI problems. Strong background in mathematics and machine learning libraries is required."
    },
    {
        id: "job-110",
        title: "Marketing Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹20k–₹30k/month",
        skills: ["Social Media", "Content Writing", "Analytics"],
        source: "Naukri",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Assist the marketing team in campaign execution and social media management. Creativity and wit are highly valued here."
    },
    {
        id: "job-111",
        title: "Operations Intern",
        company: "Uber",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹35k–₹50k/month",
        skills: ["Operations", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        applyUrl: "#",
        description: "Optimize city operations and driver partner engagement. Data-driven decision making and hustler mindset required."
    },
    {
        id: "job-112",
        title: "Android Dev Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹45k–₹70k/month",
        skills: ["Kotlin", "Android Studio", "Java"],
        source: "PhonePe Careers",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Work on the PhonePe Android app used by millions. Learn about secure coding, performance optimization, and custom UI components."
    },
    {
        id: "job-113",
        title: "Product Intern",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        salaryRange: "₹30k–₹50k/month",
        skills: ["Product Sense", "Analytics", "Wireframing"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Assist Product Managers in defining features and analyzing user feedback. Great entry point into Product Management for e-commerce."
    },
    {
        id: "job-114",
        title: "HR Intern",
        company: "Wipro",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹15k–₹20k/month",
        skills: ["Recruitment", "Communication", "Excel"],
        source: "Naukri",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Support the talent acquisition team in scheduling interviews and managing candidate databases. Good communication skills are a must."
    },
    {
        id: "job-115",
        title: "Cybersecurity Intern",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹20k–₹30k/month",
        skills: ["Networking", "Linux", "Python"],
        source: "Infosys Careers",
        postedDaysAgo: 8,
        applyUrl: "#",
        description: "Learn about network security and vulnerability assessment at Infosys. Training provided on latest security tools."
    },

    // --- JUNIOR / 0-1 YEARS (16-30) ---
    {
        id: "job-201",
        title: "Junior Backend Developer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1 Years",
        salaryRange: "8–12 LPA",
        skills: ["Python", "PostgreSQL", "Redis"],
        source: "Zerodha Careers",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Build robust backend systems for India's largest stock broker. We value clean code and understanding of underlying systems over frameworks."
    },
    {
        id: "job-202",
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "4.5–6.5 LPA",
        skills: ["Java", "Spring Boot", "SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Design, build, and configure applications to meet business process and application requirements. Good knowledge of Java ecosystem required."
    },
    {
        id: "job-203",
        title: "Frontend Developer I",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "10–14 LPA",
        skills: ["React Native", "JavaScript", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Work on the partner and customer apps. We heavily use React Native. Looking for devs who care about 60fps UI and smooth interactions."
    },
    {
        id: "job-204",
        title: "Analyst - Data Science",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "6–9 LPA",
        skills: ["Python", "Tableau", "Statistics"],
        source: "Indeed",
        postedDaysAgo: 9,
        applyUrl: "#",
        description: "Support audit and assurance teams with data analytics. creating visualizations and predictive models."
    },
    {
        id: "job-205",
        title: "Support Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "5–8 LPA",
        skills: ["Troubleshooting", "SaaS", "Ruby"],
        source: "Freshworks Careers",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Provide technical support to our global customer base. Debug issues, read logs, and write code fixes where applicable."
    },
    {
        id: "job-206",
        title: "Associate Consultant",
        company: "KPMG",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "5–7 LPA",
        skills: ["Consulting", "Research", "PPT"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Join the tech consulting practice. assist in digital transformation projects for banking clients."
    },
    {
        id: "job-207",
        title: "Junior iOS Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "8–15 LPA",
        skills: ["Swift", "UIKit", "Functional Programming"],
        source: "Juspay Careers",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Build payment SDKs used by millions. We love functional programming and writing bullet-proof code."
    },
    {
        id: "job-208",
        title: "Cloud Support Associate",
        company: "AWS",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "10–14 LPA",
        skills: ["Linux", "Networking", "AWS"],
        source: "Amazon Jobs",
        postedDaysAgo: 7,
        applyUrl: "#",
        description: "Troubleshoot complex cloud issues for AWS customers. Deep dive into networking, OS, and database concepts."
    },
    {
        id: "job-209",
        title: "System Engineer",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "3.6–5 LPA",
        skills: ["Python", "SQL", "Unix"],
        source: "Naukri",
        postedDaysAgo: 0,
        applyUrl: "#",
        description: "Core development and maintenance of enterprise applications. continuous learning opportunities available."
    },
    {
        id: "job-210",
        title: "Junior DevOps Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "8–12 LPA",
        skills: ["Docker", "Jenkins", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Help automate our deployment pipelines. Work with Kubernetes and CI/CD tools to ensure uptime."
    },
    {
        id: "job-211",
        title: "Programmer Analyst",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "4–6 LPA",
        skills: ["Java", ".NET", "SQL"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "#",
        description: "Develop and test software based on design specifications. Standard corporate environment with good growth stability."
    },
    {
        id: "job-212",
        title: "Junior Web Developer",
        company: "Zoho",
        location: "Tenkasi",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "4–6 LPA",
        skills: ["HTML", "CSS", "JavaScript"],
        source: "Zoho Careers",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Work from our rural office in Tenkasi. Build web apps that compete globally. serene environment, challenging work."
    },
    {
        id: "job-213",
        title: "Associate Product Manager",
        company: "Ather Energy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "12–16 LPA",
        skills: ["Product", "Data", "Engineering"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Own a slice of the connected scooter experience. Work with hardware and software teams to ship features."
    },
    {
        id: "job-214",
        title: "Technical Writer",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "6–9 LPA",
        skills: ["Writing", "Technology", "Docs"],
        source: "Indeed",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Create clear and concise documentation for Oracle Cloud products. Work closely with engineering teams."
    },
    {
        id: "job-215",
        title: "Start-up Founder's Office",
        company: "Stealth Startup",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "10–15 LPA",
        skills: ["Generalist", "Strategy", "Ops"],
        source: "Twitter/X",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Right hand to the founder. Do whatever it takes to grow the business. High chaos, high learning."
    },

    // --- MID-LEVEL / 1-3 YEARS (31-45) ---
    {
        id: "job-301",
        title: "SDE II",
        company: "ShareChat",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "25–35 LPA",
        skills: ["Golang", "Microservices", "GCP"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Scale backend systems for millions of concurrent users. Experience with high-throughput systems is preferred."
    },
    {
        id: "job-302",
        title: "Java Developer",
        company: "HDFC Bank",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "12–18 LPA",
        skills: ["Java 8+", "Spring Boot", "Oracle"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "#",
        description: "Modernize core banking infrastructure. Work on secure, transaction-heavy applications."
    },
    {
        id: "job-303",
        title: "React Developer",
        company: "Myntra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "18–25 LPA",
        skills: ["React", "Performance", "PWA"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        applyUrl: "#",
        description: "Build the fashion destination of India. Focus on web performance, PWA features, and responsive design."
    },
    {
        id: "job-304",
        title: "Data Engineer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "15–22 LPA",
        skills: ["Spark", "Python", "Kafka"],
        source: "Indeed",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Build data pipelines for vehicle telemetry data. Process terabytes of data daily."
    },
    {
        id: "job-305",
        title: "Full Stack Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "20–30 LPA",
        skills: ["React", "Spring Boot", "Postgres"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Simplify investing for India. Work on the entire stack from UI to DB. Ownership driven culture."
    },
    {
        id: "job-306",
        title: "Application Developer",
        company: "IBM",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "10–15 LPA",
        skills: ["Cloud", "Node.js", "K8s"],
        source: "IBM Careers",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Develop cloud-native applications for enterprise clients. Exposure to Red Hat OpenShift is a bonus."
    },
    {
        id: "job-307",
        title: "Software Engineer",
        company: "PayPal",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "15–22 LPA",
        skills: ["JavaScript", "Node.js", "Payments"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Experience the fintech revolution. Build secure payment flows and merchant integrations."
    },
    {
        id: "job-308",
        title: "Android Engineer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "20–28 LPA",
        skills: ["Kotlin", "RxJava", "Dagger"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Handle massive traffic execution during IPL. Build resilient android apps that work on poor networks."
    },
    {
        id: "job-309",
        title: "Consultant",
        company: "Capgemini",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "8–12 LPA",
        skills: ["SAP", "ABAP", "ERP"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "#",
        description: "SAP implementation and customization for global clients. Travel opportunities available."
    },
    {
        id: "job-310",
        title: "Security Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "18–24 LPA",
        skills: ["Network Security", "Python", "Firewalls"],
        source: "Cisco Careers",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Secure the networks of the future. vulnerability research and security automation."
    },
    {
        id: "job-311",
        title: "Product Designer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "15–25 LPA",
        skills: ["UX Research", "Figma", "Design Systems"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Design complex financial workflows that feel simple. We value systems thinking and user empathy."
    },
    {
        id: "job-312",
        title: "Business Analyst",
        company: "McKinsey & Co",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "14–20 LPA",
        skills: ["Analysis", "Modeling", "Client Facing"],
        source: "Indeed",
        postedDaysAgo: 9,
        applyUrl: "#",
        description: "Knowledge center analyst role. Research and provide insights for consulting teams globally."
    },
    {
        id: "job-313",
        title: "DevOps Engineer",
        company: "Disney+ Hotstar",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "18–26 LPA",
        skills: ["AWS", "Terraform", "Scale"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Keep the stream running during the World Cup. Extreme scale infrastructure management."
    },
    {
        id: "job-314",
        title: "Python Developer",
        company: "Delhivery",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "12–18 LPA",
        skills: ["Python", "Django", "Logistics"],
        source: "Naukri",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Optimize logistics networks using Python. Solve routing and capacity planning problems."
    },
    {
        id: "job-315",
        title: "Frontend Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "20–30 LPA",
        skills: ["React", "Electron", "API"],
        source: "Postman Careers",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Build the tool that 20 million developers use. Complex UI challenges in a collaborative environment."
    },

    // --- EXPERIENCED / 3-5 YEARS (46-60) ---
    {
        id: "job-401",
        title: "Senior SDE",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "40–60 LPA",
        skills: ["Java", "Distributed Systems", "Scale"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Build tools like Jira and Confluence. Remote-first culture with challenging technical problems."
    },
    {
        id: "job-402",
        title: "Tech Lead",
        company: "Lenskart",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "35–50 LPA",
        skills: ["Architecture", "Team Lead", "Node.js"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "#",
        description: "Lead a pod of developers. Omni-channel retail tech challenges."
    },
    {
        id: "job-403",
        title: "Senior Android Dev",
        company: "Truecaller",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        skills: ["Android", "Performance", "Kotlin"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Work on an app used by almost everyone in India. Focus on privacy and battery optimization."
    },
    {
        id: "job-404",
        title: "Data Scientist",
        company: "InMobi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "25–40 LPA",
        skills: ["ML", "AdTech", "Big Data"],
        source: "Indeed",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Ad-tech algorithms for real-time bidding. Work with massive datasets and low latency requirements."
    },
    {
        id: "job-405",
        title: "Senior DevOps",
        company: "BrowserStack",
        location: "Mumbai",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        skills: ["Virtualization", "Cloud", "Monitoring"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Manage thousands of diverse devices and browsers in the cloud. High reliability engineering."
    },
    {
        id: "job-406",
        title: "Product Manager",
        company: "Cleartrip",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "25–35 LPA",
        skills: ["Travel", "UX", "Roadmap"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "#",
        description: "Revamp the travel booking experience. Data driven product management."
    },
    {
        id: "job-407",
        title: "Senior Frontend Engineer",
        company: "Salesforce",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "35–55 LPA",
        skills: ["LWC", "JavaScript", "Enterprise"],
        source: "Salesforce Careers",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Build enterprise software that powers the world. Work on the core CRM platform UI."
    },
    {
        id: "job-408",
        title: "Database Administrator",
        company: "National Stock Exchange",
        location: "Mumbai",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "15–25 LPA",
        skills: ["Oracle", "Performance Tuning", "Finance"],
        source: "Naukri",
        postedDaysAgo: 4,
        applyUrl: "#",
        description: "Critical infrastructure management for the stock exchange. Zero downtime tolerance."
    },
    {
        id: "job-409",
        title: "Senior UX Researcher",
        company: "Microsoft",
        location: "Noida",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        skills: ["User Studies", "Ethnography", "Design"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        applyUrl: "#",
        description: "Understand the next billion users. Conduct field studies and inform product strategy."
    },
    {
        id: "job-410",
        title: "Engineering Manager",
        company: "BookMyShow",
        location: "Mumbai",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "35–50 LPA",
        skills: ["Leadership", "Hiring", "Architecture"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "#",
        description: "Lead the payments or events team. High traffic bursts during blockbuster releases."
    },
    {
        id: "job-411",
        title: "Senior Java Developer",
        company: "Morgan Stanley",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "28–42 LPA",
        skills: ["Java", "Multithreading", "Finance"],
        source: "Indeed",
        postedDaysAgo: 5,
        applyUrl: "#",
        description: "Low latency trading systems. Deep understanding of JVM internals required."
    },
    {
        id: "job-412",
        title: "Solutions Architect",
        company: "MongoDB",
        location: "Gurgaon",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        skills: ["NoSQL", "Architecture", "Presales"],
        source: "MongoDB Careers",
        postedDaysAgo: 0,
        applyUrl: "#",
        description: "Help customers design scalable schemas. Technical consulting role."
    },
    {
        id: "job-413",
        title: "Senior iOS Engineer",
        company: "Hotstar",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        skills: ["iOS", "Video Streaming", "Swift"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "#",
        description: "Build the best video streaming experience on iOS. Optimize for battery and data usage."
    },
    {
        id: "job-414",
        title: "Cyber Security Analyst",
        company: "PwC",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "15–22 LPA",
        skills: ["Audit", "Compliance", "Security"],
        source: "Naukri",
        postedDaysAgo: 6,
        applyUrl: "#",
        description: "Information security auditing for large clients. ISO 27001 and GDPR compliance knowledge needed."
    },
    {
        id: "job-415",
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "40–70 LPA",
        skills: ["Solidity", "Ethereum", "Cryptography"],
        source: "Web3 Careers",
        postedDaysAgo: 1,
        applyUrl: "#",
        description: "Work on the leading L2 scaling solution. Deep protocol level work."
    }
];

// Helper to simulate fetching
function getJobs() {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(JOBS_DATA);
        }, 300); // Simulate network delay
    });
}
